### ISSUE TITLE
Petal Labels...

### ISSUE THREAD

**Issue by 36bydesign** [drinkius/flowerchart#1]
It'd be great if we could have labels displayed either on the petals themselves or just outside the corresponding petals. Is this a realistic possibility? Your flowerchart is vastly underrated.

**Comment by drinkius** [comment]
Thanks for the comment! Working on a solution now to add rounded text beside the petals around the chart, expect this feature soon!

**Comment by drinkius** [comment]
Added displayLabels method, solution borrowed from the Grimxn's answer here: http://stackoverflow.com/questions/32771864/draw-text-along-circular-path-in-swift-for-ios

It's a draft version, soon to be improved - please take a look and tell me if its what you've been looking for!
