### ISSUE TITLE
Better README.md

### ISSUE THREAD

**Issue by lfarah** [drinkius/flowerchart#2]
Hey, I loved your library and for it to be perfect we just needed to work a little bit more on the `README.md`.
You can use [this README project](https://github.com/awesome-labs/iOS-readme-template) as an example

**Comment by drinkius** [comment]
Hey Lucas, thanks! Just updated the README according to the specification you provided, valuable piece of advice

**Comment by lfarah** [comment]
That's amazing. Congrats!
